language: python
python:
- 2.7
install:
- pip install .
- pip install -r requirements.txt
script:
- make build
- make dev
- make docs
- make test
after_success:
- if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh
  ./scripts/travisPublishDocs.sh; fi
- coveralls
env:
  global:
    secure: QHjNzr10PO3+ooKsFu5QUmcgua8BzkVknItzFRLHE9kn0UkfVsHqnpatgChBQMbCf6KkMTKCs/oVBvZgFFNMj+j2XCtiEwZvUYikx9PoUa9kGZkPQSHrjpiabEz33lQAkwAPIYiEmfUTRkbmulrBWZ6Ro2enaaMe/Cu3drtEEvzcnKjZ3Y/mxel3mu4APiDGPqpyPoK/irybeJcsjXV6tqsBPP+QGjodmfI+MXOVgSyCM9wL43oBpWJbPgZPciqNm7UWT4fJf3L22YKp7w89dMrOYAVgwIhHDbJOF6C7jsVzG01ri/WktmepH1TLcdLE4xypw9jEJgUjT6AW6fFBo9DKSaV+XS3bjzX3SmvEbvlQh5XDCmtVwpxfTSjGRseT2+16asrsctvYGQ+iBIZc+70GU49INHAYVaq9dvJYOkgnm+tkULy4PHXTYCwwTYFe3x/sRQaqeJRzajkyKEIZqn4GVjCR3r8oCoD5mrvm/Ujo7rUBIfgsECTvgLiEXCYECUHJTI0MmCvSNklkAQNt1N++uTzaAty7PRNUImWUOpEWJ2eyk0DTwYJpZKlV8XeEeC2b+i0jMoTjuFvN6xBAvvDNbuF7gNEvQPvaqcfCyc/AdzNyWPcXUIJ47tRSQBF2mcLGCROZBdkl4WhZDX8I18oRNKZhfwdHskbqJ+mFCzs=
