language: python
python:
- 2.7
install:
- pip install .
- pip install -r requirements.txt
script:
- make build
- make dev
- make docs
- make test
after_success:
- if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh
  ./scripts/travisPublishDocs.sh; fi
- coveralls
env:
  global:
    secure: CvGSBuKgxFxNvNlV3iIZUD5OJB2EA2bhh0JVIYRfiY3LaYoxQra8GORKGUtqfAcBkuVMKdoqUS5dzd39MxyvMU1dVC6jau/Uy6LO3FcoVc0mD4H7ayBTqovxNEb2lfp1TnNmEsTN2yypmgqogfpD4twgri3PoKF6PUlXSFsHqDcTnzmhbLnngf27Nql+VVJPjDQONdcltZQlzkxdZ/KO/tfpVfFof+o8krooGS2J8n+mmaNq8KHWBFC016SOAxGmzf+pYjiCgdCLJw5rLlvvVRR7z6cco0GMgBx3C6S6UqNLeBle805nxxsoycUwEXexV3q3f/sXvOfcWs5qLRgOMKwxHSuoB7cIaFJFWFDdFeOIYhuHC4dR801TzdJx23228C05uTbRUo5bx9qK3z/lr2f11YW99w/MYuJXteBQKAYmiuXPqiABiYly+9B6K4yQqlJIDBN7CcVKg51n8750SKTLLK9pqlNxA5KEDd+Tdv4ygmqByyzvXSflBMFM9TPuQqUK+CT31hEsNl7PwsrT63dFb0DDv72gRpV9W3EA0I170lHqDIypHyzSjtwp4c5LkKgtvBSAG+y7RY6yH7sVH2SynL2L5NH7NOzOjv7dKK1DCX98axV7NmqqDCzT4ovrS2T2mLaoKmLbnlaWri7sk85ACaVSBTao9Rd7dbZkwbo=
