language: python
python:
- 2.7
install:
- pip install .
- pip install -r requirements.txt
script:
- make build
- make dev
- make docs
- make test
after_success:
- if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh ./scripts/travisPublishDocs.sh; fi
- coveralls