language: python
python:
- 2.7
install:
- pip install .
- pip install -r requirements.txt
script:
- make build
- make dev
- make docs
- make test
after_success:
- if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh
  ./scripts/travisPublishDocs.sh; fi
- coveralls
env:
  global:
    secure: br3I8yownqQ8JN9m8rCGLBlPKXCVLFvvULU2YAnthYyIXpbON+XtvUxP8GBh8AZ0sYVqukMjiVzr7EauZzzXHcvoQWo80KQTNwry0Mq0oKFnzNh5soavQGKbXMUjZkLpF1cNrWhQ4hLntHhEwRDP002MB4Km4EQ1jTcKqhD1YE//0BTUVGwNuVfbbXMYPthqIaMI9aX8hi9a6bz4E5K87r1Qfj7lmzXFvHuJR51zDL89tbPj+/oUDHyvTUO6Kev3dfCF9QVvbPR0HFmdtutnCdnS7fd+iHM5Y6Bayvpv44YfD4Dzi7ExV/Nz1nghyp0n8GNi7eijf7+uVBDljg4SMXm4iTxNPfmi0Rq3CBbBgRRQjdvePY8XRr5YSXdh/Cc/z9D2lXaJMkyv1PcOTaBakwu6NghYccZulmFjo0KIIH99E/W4/HMJJjwezWKI+z8mABcZH0KQNEupB6661Dtlh7Pn8zPDw8MEsgbk0YO8q35lwUqHRA8q2DIVJoB+vgX+REzntqATfNoqd5C86TgultdpggcVClAcVhWz5nJSN6Tz1rc3awbZ3NxXynl0cAjO2p6+HN9iRBiEDE5sfHxfSu+M5cYjNcNX4OYA9U0PDZZjyi0IM1yVvfY92Fi9P/JILNQ6Rp1XB4ZSikGRU5CtPlQAY7rIQTxdg3jrRbk48ak=
